name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: 8ddfc1f85b86d2df52ee605200e3a4c75e423eca
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
